# Generated by Django 3.0.6 on 2020-05-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puser',
            name='pubg_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
