# Generated by Django 3.0.6 on 2020-05-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='p_user',
            field=models.ManyToManyField(to='myapp.PUser'),
        ),
    ]
