# Generated by Django 3.0.6 on 2020-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tournament_p_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='p_user',
            field=models.ManyToManyField(blank=True, to='myapp.PUser'),
        ),
    ]
