# Generated by Django 3.0.6 on 2020-05-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tournament_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='puser',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
